version: "3.8"
services:
  mysql_db:
    image: mysql:5.7
    volumes:
      - mydatabase:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: database_container_app
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "database_container_app"
    environment:
      DB_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend/src:/app/src
    container_name: backend_container_app
    command: npm run dev
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend_container_app
    container_name: frontend_container_app
volumes:
  mydatabase: {}
